log:
  level: debug
  console_output: true
listen:
  port: 9999

file_storage:
  base_service_url: http://localhost:8181
db:
  schema: courses_service
  host: localhost
  port: 5432
  database: postgres
