basePath: /api/courses-service
definitions:
  apierrors.Error:
    properties:
      details:
        additionalProperties: {}
        type: object
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
  domain.Course:
    properties:
      authorFio:
        type: string
      id:
        type: integer
      lessons:
        items:
          $ref: '#/definitions/domain.Lesson'
        type: array
      title:
        type: string
    type: object
  domain.CourseIdRequest:
    properties:
      courseId:
        type: integer
    required:
    - courseId
    type: object
  domain.CoursePreview:
    properties:
      authorFio:
        type: string
      id:
        type: integer
      previewPictureUrl:
        type: string
      title:
        type: string
    type: object
  domain.EditUserRequest:
    properties:
      fio:
        maxLength: 60
        minLength: 6
        type: string
      password:
        maxLength: 20
        minLength: 6
        type: string
      roleId:
        type: integer
      userId:
        type: integer
      username:
        maxLength: 50
        minLength: 4
        type: string
    required:
    - roleId
    - userId
    type: object
  domain.GetRoleResponse:
    properties:
      roleName:
        type: string
    type: object
  domain.IsRegisteredResponse:
    properties:
      isRegistered:
        type: boolean
    type: object
  domain.Lesson:
    properties:
      createdAt:
        type: string
      lessonContent:
        type: string
      lessonNumber:
        type: integer
      title:
        type: string
      videoUrl:
        type: string
    type: object
  domain.LoginRequest:
    properties:
      password:
        maxLength: 20
        minLength: 6
        type: string
      username:
        maxLength: 50
        minLength: 4
        type: string
    type: object
  domain.LoginResponse:
    properties:
      sessionId:
        type: string
    type: object
  domain.RegisterRequest:
    properties:
      fio:
        maxLength: 60
        minLength: 6
        type: string
      password:
        maxLength: 20
        minLength: 6
        type: string
      roleId:
        type: integer
      username:
        maxLength: 50
        minLength: 4
        type: string
    required:
    - roleId
    type: object
  domain.Role:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  domain.Session:
    properties:
      createdAt:
        type: string
      id:
        type: string
    type: object
  domain.User:
    properties:
      fio:
        type: string
      id:
        type: integer
      roleId:
        type: integer
      roleName:
        type: string
      username:
        type: string
    type: object
  domain.UserProfile:
    properties:
      fio:
        type: string
      id:
        type: integer
      roleId:
        type: integer
      roleName:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: Сервис для записи на курсы
  title: courses-service
  version: 1.0.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: тело запроса
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.LoginResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      summary: Войти в аккаунт
      tags:
      - auth
  /auth/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      security:
      - Bearer: []
      summary: Завершить сессию
      tags:
      - user
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: тело запроса
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      summary: Зарегистрировать пользователя
      tags:
      - auth
  /auth/sessions:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Session'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      security:
      - Bearer: []
      summary: Завершить сессию
      tags:
      - user
  /auth/terminate_session:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      security:
      - Bearer: []
      summary: Завершить сессию
      tags:
      - user
  /courses:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.CoursePreview'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      summary: Получить список курсов
      tags:
      - course
  /courses/by_id:
    get:
      consumes:
      - application/json
      parameters:
      - description: идентификатор курса
        in: query
        name: courseId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Course'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      summary: Получить курс
      tags:
      - course
  /courses/is_registered:
    get:
      parameters:
      - description: идентификатор курса
        in: query
        name: courseId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.IsRegisteredResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      security:
      - Bearer: []
      summary: Проверить зарегистрирован пользователь на курс
      tags:
      - course
  /courses/register:
    post:
      parameters:
      - description: тело запроса
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.CourseIdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      security:
      - Bearer: []
      summary: Зарегистрироваться на курс
      tags:
      - course
  /courses/user_courses:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.CoursePreview'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      security:
      - Bearer: []
      summary: Получить курсы пользователя
      tags:
      - course
  /roles:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Role'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      summary: Получить список ролей
      tags:
      - role
  /users:
    delete:
      parameters:
      - description: максимальное количество записей
        in: query
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      security:
      - Bearer: []
      summary: Удалить пользователя
      tags:
      - user
    get:
      parameters:
      - description: максимальное количество записей
        in: query
        name: limit
        required: true
        type: integer
      - description: отступ поиска записей
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      security:
      - Bearer: []
      summary: Получить пользователей
      tags:
      - user
    post:
      parameters:
      - description: тело запроса
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.EditUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/apierrors.Error'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      security:
      - Bearer: []
      summary: Редактировать профиль пользователя
      tags:
      - user
  /users/get_role:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetRoleResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      security:
      - Bearer: []
      summary: Получить роль пользователя
      tags:
      - user
  /users/profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.UserProfile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/apierrors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.Error'
      security:
      - Bearer: []
      summary: Получить профиль пользователя
      tags:
      - user
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and session id.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
